version: '3'

services:
  # app:
  #   container_name: node-api
  #   build: ./api
  #   environment:
  #     - NODE_ENV=production
  #     - MONGO_DATABASE=mongodb://mongodb/myapp
  #   volumes:
  #     - ./api:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - 8080:8080
  #   tty: true
  #   links:
  #     - mongodb

  app:
    container_name: node-mongoose-test
    build: ./mongoose-test
    environment:
      - NODE_ENV=production
      - MONGO_DATABASE=mongodb://mongodb/myapp
    volumes:
      - ./mongoose-test:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:8080
    tty: true
    links:
      - mongodb

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    command:
      - mongod

  # どうやって別のポートで立ち上げるんだ
  # mongodb2:
  #   image: mongo:latest
  #   environment:
  #     - MONGO_DATA_DIR=/data/db
  #     - MONGO_LOG_DIR=/dev/null
  #   ports:
  #     - 27018:27018
  #   command:
  #     - mongod --port 27018
