version: '3'

services:
  app:
    container_name: node-api
    build: ./api
    volumes:
      - ./api:/usr/src/app
    ports:
      - 8080:8080
    tty: true
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:3.4
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017
