version: '3'

services:
  # app:
  #   container_name: node-api
  #   build: ./api
  #   environment:
  #     - NODE_ENV=production
  #     - MONGO_DATABASE=mongodb://mongodb/myapp
  #   volumes:
  #     - ./api:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - 8080:8080
  #   tty: true
  #   links:
  #     - mongodb

  app:
    container_name: node-mongoose-test
    build: ./mongoose-test
    environment:
      - NODE_ENV=production
      - MONGO_DATABASE=mongodb://mongodb/myapp
      - MONGO_DATABASE2=mongodb://mongodb2/myapp
    volumes:
      - ./mongoose-test:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:8080
    tty: true
    links:
      - mongodb
      - mongodb2

  # ローカルホストの27017 portと繋ぐ
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    # すでにportを使っている場合はホストマシン側のportを変更する
    ports:
      - 27017:27017
    command:
      - mongod

  # ローカルホストの27018 portと繋ぐ
  mongodb2:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    # すでにportを使っている場合はホストマシン側のportを変更する
    ports:
      - 27018:27017
    command:
      - mongod
